apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myingressresource
spec:
  tls:
  - hosts:
    - razee-demo-01.us-south.containers.appdomain.cloud
    secretName: razee-demo-01
  rules:
  - host: razee-demo-01.us-south.containers.appdomain.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80

