apiVersion: v1
kind: List
metadata:
  name: razeedash-api
  namespace: armada
  annotations:
    version: (( grab $TRAVIS_COMMIT || "dev" ))
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        version: (( grab $TRAVIS_COMMIT || "dev" ))
        razee.io/git-repo: (( grab $GIT_REMOTE ))
        razee.io/commit-sha: (( grab $TRAVIS_COMMIT ))
      name: razeedash-api 
      namespace: armada
      labels:
        razee/restart-on-config-change: "true"
    spec:
      replicas: 2
      revisionHistoryLimit: 0
      selector:
        matchLabels:
          app: razeedash-api 
      strategy:
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: razeedash-api 
          name: razeedash-api 
        spec:
          containers:
          - env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: razeedash-secret
                  key: mongo_url
            - name: MONGO_DB_NAME
              value: razeedash
            image: (( concat "{{ DOCKER_REGISTRY }}/armada/ razeedash-api:" metadata.annotations.version ))
            imagePullPolicy: Always
            name: razeedash-api 
            ports:
            - containerPort: 3333
              protocol: TCP
            livenessProbe:
              httpGet:
                path: /kube/liveness
                port: 3333
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 2
            # readinessProbe:
            #   httpGet:
            #     path: /kube/readiness
            #     port: 3000
            #   initialDelaySeconds: 5
            #   periodSeconds: 10
            #   timeoutSeconds: 2

  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        version: (( grab $TRAVIS_COMMIT || "dev" ))
        prometheus.io/probe: 'true'
        prometheus.io/probepath: 'metrics'
        prometheus.io/scrape: 'true'
        razee.io/git-repo: (( grab $GIT_REMOTE ))
        razee.io/commit-sha: (( grab $TRAVIS_COMMIT ))
      name:  razeedash-api-service
      namespace: armada
    spec:
      selector:
        app: razeedash-api 
      ports:
       - protocol: TCP
         port: 8081
         targetPort: 3333
  - apiVersion: autoscaling/v1
    kind: HorizontalPodAutoscaler
    metadata:
      name:  razeedash-api-scaler
      namespace: armada
      annotations:
        version: (( grab $TRAVIS_COMMIT || "dev" ))
        razee.io/git-repo: (( grab $GIT_REMOTE ))
        razee.io/commit-sha: (( grab $TRAVIS_COMMIT ))
    spec:
      scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: razeedash-api 
      minReplicas: 5
      maxReplicas: 15
      targetCPUUtilizationPercentage: 70
